### ISSUE TITLE
Add Support for Snipmate

### ISSUE THREAD

**Issue by dohsimpson** [sebosp/vim-snippets-terraform#1]
Thanks for the great work! This is the most complete terraform snippet I found. I use snipmate instead of ultisnip. But it takes less than half an hour to support snipmate snippets. Here you go.

**Comment by dohsimpson** [comment]
PR: https://github.com/sebosp/vim-snippets-terraform/pull/2

**Comment by sebosp** [comment]
Thanks for the suggestion, PR has been merged.
